spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 기본은 local

  application:
    name: solply-server

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Seoul
          default_schema: public
          batch_size: 25

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info