appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(executionTime)ms | %(sqlSingleLine)

# 커넥션 획득, 트랜잭션 이벤트, 결과셋 등 제외
filter.multiline=false
excludecategories=info,debug,result,resultset,batch,commit,rollback

# HikariCP keepalive 쿼리 제외
excludestatements=SELECT 1
