name: Bug Template
description: 버그 제보
title: "[Fix] Bug Title"
labels: ["fix"]

body:
  - type: textarea
    id: bug-contents
    attributes:
      label: 💬 이슈 설명
      description: 자세한 버그 혹은 수정해야 할 부분에 대해 설명해 주세요.
      placeholder: "ex. !!! 상황에서 ~~~한 버그가 난다."
    validations:
      required: true
  - type: textarea
    id: solve-steps
    attributes:
      label: 🔨작업 내용
      description: 작업해야 할 내용을 체크박스 형태로 작성해주세요.
      value: |
        - [ ] 작업
        - [ ] 
        - [ ]
    validations:
      required: true