
-- =================================================================
-- towns
-- =================================================================
INSERT INTO towns (id, parent_id, name) VALUES
                                            (1, NULL, '서울'),
                                            (2, 1, '연희동'),
                                            (3, 1, '망원동');

-- =================================================================
-- tags
-- =================================================================
INSERT INTO tags (id, parent_id, name, type) VALUES
                                                 (1, NULL, 'CAFE', 'MAIN'),
                                                 (2, NULL, 'FOOD', 'MAIN'),
                                                 (3, NULL, 'SHOPPING', 'MAIN'),
                                                 (4, NULL, 'BOOKSTORE', 'MAIN'),
                                                 (5, NULL, 'UNIQUE_SPACE', 'MAIN'),
                                                 (6, NULL, 'WALKING', 'MAIN'),
                                                 (7, 1, 'COFFEE_DESSERT', 'OPTION1'),
                                                 (8, 1, 'WORK', 'OPTION1'),
                                                 (9, 1, 'READING', 'OPTION1'),
                                                 (10, 1, 'HEALING', 'OPTION1'),
                                                 (11, 1, 'SIGNATURE_MENU', 'OPTION2'),
                                                 (12, 1, 'MOOD_INTERIOR', 'OPTION2'),
                                                 (13, 1, 'SUNLIGHT', 'OPTION2'),
                                                 (14, 1, 'MANY_PLUG', 'OPTION2'),
                                                 (15, 1, 'NO_TIME_LIMIT', 'OPTION2'),
                                                 (16, 1, 'BAR_TABLE', 'OPTION2'),
                                                 (17, 2, 'KOREAN_FOOD', 'OPTION1'),
                                                 (18, 2, 'CHINESE_FOOD', 'OPTION1'),
                                                 (19, 2, 'JAPANESE_FOOD', 'OPTION1'),
                                                 (20, 2, 'WESTERN_FOOD', 'OPTION1'),
                                                 (21, 2, 'BAR', 'OPTION1'),
                                                 (22, 2, 'BAKERY', 'OPTION1'),
                                                 (23, 2, 'ASIAN_FOOD', 'OPTION1'),
                                                 (24, 2, 'SINGLE_MENU', 'OPTION2'),
                                                 (25, 2, 'SELF_SERVICE', 'OPTION2'),
                                                 (26, 5, 'ART', 'OPTION1'),
                                                 (27, 5, 'WORKSHOP', 'OPTION1'),
                                                 (28, 3, 'LIFESTYLE_SHOP', 'OPTION1'),
                                                 (29, 3, 'VINTAGE_SHOP', 'OPTION1'),
                                                 (30, 3, 'POPUP_MARKET', 'OPTION1');

-- =================================================================
-- place
-- =================================================================
INSERT INTO places (id, latitude, longitude, place_default_id, town_id, address, contact_number, introduction, name, opening_hours, place_type, created_at, updated_at) VALUES
                                                                                                                                                                            (1, 37.5598517, 126.9063944, 1615953308, 2, '서울 마포구 월드컵로 133 2층 차차', NULL, '한낮의 고요가 머무는 망원동 브런치 카페', '차차', '12:00 - 19:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (2, 37.5536351, 126.9034259, 1815597250, 2, '서울 마포구 망원로2길 82 1층 포스트노빌즈', '010-4439-0430', '그레이 톤에 스며드는 조용한 휴식', '포스트 노 빌즈', '12:00 - 22:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (3, 37.5523415, 126.9062382, 1039371174, 2, '서울 마포구 동교로 34 2층 전부', '02-0001-1234', '정성스레 완성한 편안한 하루의 시작', '로잉커피', '화, 수, 목, 금 11:00 - 22:00\n토, 일 9:00 - 22:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (4, 37.5527719, 126.904881, 1886457037, 2, '서울 마포구 희우정로10안길 7 1층', '0507-1477-9597', '소품과 온기가 있는 골목 속 쉼터', '꼬레소레하우스', '수, 목 15:00 - 20:00\n금 14:00 - 20:00\n토, 일 12:00 - 20:00\n매주 월, 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (5, 37.5601556, 126.9034709, 1373662518, 2, '서울 마포구 방울내로 72 1층 도래노트', '0507-1368-1062', '간판 없이도 찾게 되는 깊은 맛의 커피', '도래노트', '월 11:00 - 18:00 / 17:30 라스트오더\n화, 수, 금, 토, 일 10:00 - 18:00 / 17:30 라스트오더\n매주 목 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (6, 37.5550175, 126.9050447, 1106679886, 2, '서울 마포구 포은로 89 1층', '010-9877-3754', '작고 귀여운 것들이 가득한 망원 놀이터', '놀이터 가챠', '10:00 - 21:00\n매주 목 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (7, 37.556395, 126.9057659, 1259081266, 2, '서울 마포구 포은로8길 16 1층 mood', '010-6454-3005', '망원동 작은 공방, 향을 담아가는 시간', '무드', '수, 목, 금 11:00 - 20:00\n월, 화, 토, 일 12:00 - 20:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (8, 37.5567556, 126.9081659, 2084531481, 2, '서울 마포구 월드컵로19길 16 지층', '0507-1386-0117', '정성 가득 일본 가정식, 한 상의 위로', '나고미칸', '11:30 - 21:00 / 15:00 - 17:00 브레이크타임 / 14:20 , 20:20 라스트오더\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (9, 37.5525062, 126.9067386, 2082067976, 2, '서울 마포구 동교로 40 1층', '010-3815-6282', '작은 위로를 담은 따뜻한 일본식 카레 한 그릇', '츠부카레', '11:00 - 21:00 / 16:00 - 17:00 브레이크타임 / 20:30 라스트오더\n매주 일 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (10, 37.5569313, 126.9083062, 1092853138, 2, '서울 마포구 월드컵로19길 12 102호', NULL, '건강한 한 끼, 따뜻한 오차즈케 한 상', '모구모구', '11:15 - 20:30 / 14:30 - 17:30 브레이크타임 / 14:00, 20:00 라스트오더\n매주 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (11, 37.554355, 126.9069268, 449030953, 2, '서울 마포구 월드컵로19길 74 어쩌다가게 지하 2층', '0507-1335-2707', '토마토육개장의 새로운 매력을 느낄 수 있는 곳', '육장', '11:00 - 20:00 / 15:00 - 17:00 브레이크타임 / 19:40 라스트오더', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (12, 37.5615191, 126.901324, 1628736383, 2, '서울 마포구 방울내로7길 41-9 1층', '0507-1421-5963', '자연의 결을 담은 친환경 오브제 체험 공방', '오브제시수', '13:00 - 19:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (13, 37.5581809, 126.9009893, 1701247901, 2, '서울 마포구 망원로3길 34 2층', '0507-1365-7731', '향기와 빛으로 완성하는 특별한 공방 클래스', '향긋빵긋', '12:00 - 19:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (14, 37.5584252, 126.907621, 1023107117, 2, '서울 마포구 월드컵로 113 3층 301호', NULL, '계절의 변화를 담아 읽고 쓰는 작은 공간', '계절책방 낮과밤', '화,수,토 13:00 - 19:00\n목, 금 15:00 -21:00\n매주 일, 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (15, 37.5572559, 126.9051913, 473585128, 2, '서울 마포구 망원로 74-1 지하 1층', '010-5769-0377', '북토크와 공연, 책으로 채우는 따뜻한 순간', 'gaga77page', '13:00 - 20:00 \n매주 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (16, 37.5543211, 126.9086097, 1128518749, 2, '서울 마포구 월드컵로11길 44 102호', '0507-1420-5574', '커피의 향과 책의 즐거움이 머무는 서점', '스캐터북스', '12:00 - 20:30\n매주 수 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (17, 37.5564182, 126.9048511, 898151104, 2, '서울 마포구 포은로 106', '0507-1468-1395', '오늘을 달콤하게 만드는 젤라또 가게', '당도', '12:00 - 21:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (18, 37.5543287, 126.9058772, 1699285067, 2, '서울 마포구 망원로8길 73 1층 우측', NULL, '취향을 수집하는 감도 높은 편집숍', '아우어리틀룸', '월, 수, 금, 토, 일 13:30 - 20:00\n목 14:00 - 20:00\n매주 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (19, 37.5553579, 126.9041169, 1892102305, 2, '서울 마포구 포은로5길 15 2층', '0507-1373-2605', '함께 좋아하는 것들로 채운 취향의 숍', '떠블유떠블유', '월 15:00 - 22:00 \n화, 수, 목, 금, 토 13:00 - 22:00\n일 13:00 - 19:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (20, 37.5545448, 126.9037631, 1027672585, 2, '서울 마포구 희우정로16길 32', '0507-1350-7561', '지구, 여행, 사랑이 담긴 디자인 공간', '제로스페이스', '월, 화, 수, 목, 금, 일 12:00 - 19:30\n토 12:00 - 20:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (21, 37.5544848, 126.9055227, 1470625379, 2, '서울 마포구 포은로 84 2층', '0507-1357-7849', '좋은 물건과의 우연한 만남', '디스커버 굿 굿즈', '13:00 - 20:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (22, 37.5575666, 126.9042438, 1762195663, 2, '서울 마포구 포은로 119 1층 호코리상점', '0507-1337-7910', '잊고 있던 시절을 꺼내는 추억의 상점', '호코리상점', '13:00 - 19:00\n매주 월 정기휴무\n(1인 가게로 유동적일 수 있으니 인스타 참고)', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (23, 37.5565057, 126.9018972, 1019045742, 2, '서울 마포구 망원로4길 3 2층', '0507-1444-1439', '사물에 새로운 시선을 더하는 프로젝트', '더트프로젝트', '13:00 - 20:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (24, 37.5563431, 126.9081183, 1039820519, 2, '서울 마포구 월드컵로19길 25 1층', '0507-1367-0603', '밀리터리부터 워크웨어까지 빈티지맛집', '테라스웨어', '12:30 - 20:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (25, 37.5548244, 126.9051174, 1287158753, 2, '서울 마포구 포은로 87 2층', '0507-1322-6567', '망원동 골목의 정품 빈티지 스팟', 'adhouse', '12:00 - 20:30', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (26, 37.5578333, 126.9051334, 1683250530, 2, '서울 마포구 월드컵로25길 47 3층 알맹상점', '0507-1386-1064', '제로웨이스트의 모든 것, 알맹상점', '알맹상점', '12:00 - 20:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (27, 37.5561624, 126.9080235, 1161449649, 2, '서울 마포구 월드컵로19길 29 지층', '0507-1425-9670', '취향 따라 발견하는 빈티지 한 조각', '보부상', '수-일 13:00 - 20:00\n매주 월, 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (28, 37.5571654, 126.9028909, 1985110297, 2, '서울 마포구 망원로 55-3', '02-6104-9105', '자극 없이 든든하고 건강한 분식집', '샐러마리', '월, 화, 목, 금 11:00 - 19:00\n토 11:00 - 19:00 / 16:00 - 17:00 브레이크타임\n매주 수, 일 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (29, 37.5552383, 126.9097924, 1532303105, 2, '서울 마포구 동교로9길 33 1층 헤키', '070-7773-9870', '콜드스모크로 완성한 절충의 카츠', '헤키', '수, 목, 금 11:30 - 20:30 / 15:00 - 17:00 브레이크타임 / 14:30, 20:00 라스트오더\n토, 일 11:30 - 20:30 / 16:00 - 17:00 브레이크타임 / 15:30, 20:00 라스트오더\n매주 월, 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (30, 37.5675168, 126.9271517, 1859353850, 3, '서울 서대문구 연희로11가길 48-24', '0507-1401-8612', '무심코 지나온 나를 돌아보는 전시', '아이아이연희', '10:30 - 19:30\n(마지막 입장 시간 - 19:30)', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (31, 37.5683993, 126.9303223, 153796899, 3, '서울 서대문구 연희로11라길 10-6 2층 우측', '070-8821-8990', '개인의 기록이 모인 독립출판 책방', '유어마인드', '13:00 - 20:00\n매주 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (32, 37.5700065, 126.9312814, 1239700627, 3, '서울 서대문구 증가로 18 3층 305호 포셋', '0507-1329-7427', '종이 위에 마음을 남기는 문구점', '포셋', '12:00 - 20:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (33, 37.5740902, 126.9346502, 1161125870, 3, '서울 서대문구 연희로 189-16 단독주택', '0507-1324-9018', '작업하기 좋은 주택 골목 속 조용한 카페', '본지르르 연희', '12:00 - 22:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (34, 37.5672271, 126.9290697, 1792285395, 3, '서울 서대문구 연희맛로 17-14 2층 센티멘트 sentiment', '0507-1416-3070', '풍경처럼 머무는 감성의 공간, 센티멘트', '센티멘트', '화, 수, 목, 일 12:00 - 22:00\n금, 토 12:00 -23:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (35, 37.5677946, 126.9313914, 1032580297, 3, '서울 서대문구 연희로 109 2층', '0507-1389-6159', '공간도, 커피도 만족스러운 작업 카페', '프로토콜', '10:30 - 22:00 / 21:30 라스트오더', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (36, 37.5660843, 126.9305538, 1113397432, 3, '서울 서대문구 연희로 90-1 2층 202호', '0507-1383-6410', '차분한 분위기 속 한 조각의 달콤함', '고유', '10:00 - 19:00 \n매주 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (37, 37.567293, 126.9281513, 36543730, 3, '서울 서대문구 연희로11나길 7-7 반지층 카페 (푸어링아웃)', '0507-1409-5564', '진한 커피와 신청곡으로 채우는 집중시간', '푸어링 아웃', '10:00 - 22:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (38, 37.5688639, 126.9287523, 1605782172, 3, '서울 서대문구 연희로11길 57 1층', '010-9223-3484', '기록 덕후의 취향을 저격하는 문구 공간', '올라이트 연희', '월, 수, 목, 금, 토, 일 13:00 - 18:00\n매주 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (39, 37.5693942, 126.931752, 1993597385, 3, '서울 서대문구 증가로 10 402호', '02-333-1016', '편지를 쓰고 싶은 마음이 시작되는 공간', '글월 연희', '13:00 - 18:00\n(방문 전 SNS @geulwoll.kr 공지 확인 필수)', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (40, 37.5698315, 126.9313766, 1938586999, 3, '서울 서대문구 증가로 16 201호 비스켓스튜디오', '0507-1352-4408', '작은 시간을 담은 디자인과 전시의 공간', '비스켓스튜디오', '12:00 - 20:00\n매주 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (41, 37.5660431, 126.9253128, 1895201846, 3, '서울 서대문구 성산로 316 2층', '02-6013-9426', '일상 속 물건을 관찰하고 기록하는 곳', '생활수집', '12:00 - 19:00\n매주 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (42, 37.5682441, 126.929225, 57227725, 3, '서울 서대문구 연희로11길 41 1층', '02-338-0345', '숲에서 책상까지, 감각을 잇는 문구점', '그린디자인웍스 공장', '월, 화, 수, 목, 금 12:00 - 18:30\n토, 일 12:00 - 19:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (43, 37.5662742, 126.9274575, 1723371114, 3, '서울 서대문구 연희로11가길 53 1층', '0507-1433-9334', '연희동에서 만나는 진짜 수제버거 맛', '링키지 버거', '11:30 - 20:00 / 16:00 - 17:00 브레이크타임 / 15:30, 19:30 라스트오더', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (44, 37.5789902, 126.9352439, 1676099957, 3, '서울 서대문구 홍제천로 200-5 2층 2호', '010-3339-0124', '오직 한 팀만을 위한 예약제 책방', '연희사과', '10:00 - 22:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (45, 37.5798275, 126.9356883, 1430069445, 3, '서울 서대문구 연희동 170-181', NULL, '도심 속 시원한 쉼표, 홍제천 인공폭포', '홍제천 인공폭포', 'x', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (46, 37.5678022, 126.9296332, 1588617978, 3, '서울 서대문구 연희로11길 29 1층 베어브레드', '0507-1432-4412', '정성 가득한 건강한 식사빵 전문점', '베어 브레드', '수, 목, 금, 토 10:00 - 21:00 \n일 13:00 - 21:00\n매주 월, 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (47, 37.5667448, 126.9281096, 1051152758, 3, '서울 서대문구 연희로11가길 39 1층', '0507-1445-8897', '20년 커피 내공이 녹아든 에스프레소 바', '연희에스프레소바', '9:30 - 21:00 / 20:30 라스트오더', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (48, 37.5670966, 126.929608, 1359419409, 3, '서울 서대문구 연희맛로 23 1층 13호 랄라루들', '0507-1463-0435', '얼큰하고 따뜻한 연희동 사천식 중식당', '랄라루들', '11:00 - 20:30 / 15:00 - 16:00 브레이크타임 / 20:00 라스트오더\n(재료 소진 시 조기 마감)', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (49, 37.5682774, 126.9300978, 1032831810, 3, '서울 서대문구 연희로11라길 10-2 1층 khakis', '070-4048-3500', '다채로운 취향이 공존하는 복합 셀렉트숍', '카키스 연희', '13:00 - 20:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (50, 37.5705465, 126.9303121, 1619030373, 3, '서울 서대문구 증가로 27 1층', '0507-1414-7665', '블루로 물든 재즈 감성의 서점 공간', '쏘블루', '12:00 - 20:00\n매주 월, 화 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (51, 37.5793854, 126.9357032, 1437596761, 3, '서울 서대문구 홍제천로 206 1층', NULL, '디자인과 커피가 공존하는 감각의 거점', '퍼스트바이쓰리', '화, 수, 목, 금, 토 10:00 - 19:00 \n매주 월, 일 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (52, 37.5658152, 126.9298027, 1212605834, 3, '서울 서대문구 연희로 83 은혜빌딩 B1층', '0507-1363-9976', '그릴드 채소 가득한 건강 샐러드 한 끼', '팔레트샐러드 연희점', '10:00 - 20:30 / 20:15 라스트오더', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (53, 37.5651731, 126.9306766, 1656206859, 3, '서울 서대문구 연희로8길 16-6 베스트빌 1층 101호', '0507-1341-2782', '커피로 사람과 가치를 잇는 공간', '그로밋커피하우스', '월, 화, 목, 금 09:00 - 19:30 \n토, 일 10:00 - 20:00\n매주 수 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (54, 37.5545631, 126.9171367, 1292205602, 3, '서울 마포구 동교로18길 13 세원빌딩 1층', '0507-1338-2044', '쌀의 담백함을 담은 깜빠뉴의 매력', '포포브레드', '12:00 - 18:00 \n일, 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (55, 37.5670966, 126.929608, 1084308470, 3, '서울 서대문구 연희맛로 23 2층 7호', '02-323-7778', '꾸미는 재미에 푹 빠질 DIY 공간', '옵젵상가', '12:00 - 20:00\n(입장 마감 시간은 저녁 7시 30분)\n매달 1,3번째 월 정기휴무', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                                                                                            (56, 37.5651675, 126.9309361, 1156408497, 3, '서울 서대문구 연희로8길 18 스페이스독 1층', '070-7780-0963', '선명하고 몰입감이 뛰어난 독립영화관', '라이카시네마', '09:00 - 23:00', 'PLACE_POI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =================================================================
-- course
-- =================================================================
INSERT INTO courses (id, name, introduction, town_id, is_shared, created_by, created_at, updated_at) VALUES
                                                                                                         (1, '나만 알고싶은 망원동 코스', '조용한 골목 사이 나만 알고싶은 공간 모음', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (2, '망원동 빈티지샵 쇼핑 코스', '나만의 스타일을 발견하는 빈티지샵 쇼핑 코스', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (3, '책과 커피의 여백', '작은 서점과 한적한 카페 사이, 생각이 머무는 공간', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (4, '제로웨이스트 라이프 코스 ', '제로웨이스트 샵과 함께하는 혼놀 코스', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (5, '감각을 따라 걷는 하루', '나만의 향과 맛, 그리고 책의 결을 담는 시간', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (6, '소품샵 탐방 코스', '소소한 소비로 챙기는 확실한 기쁨', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (7, '나만 알고 싶은 감성 코스', '나만 알고 싶은 명소 모음', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (8, '망원동 감성 명소 총정리', '걷기만 해도 기분 좋아지는 망원동 대표 감성 스팟 모음', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (9, '조용한 평일 오후 코스', '혼자 걷기 좋은 시간, 조용하고 느긋한 동네 산책', 3, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (10, '오롯이 나를 위한 하루', '아기자기한 소품샵부터 나를 찾는 1인 전시까지', 2, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (11, '도심 속 느슨한 여백', '책과 녹음이 어우러진 힐링 코스', 2, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (12, '취향을 수집하는 하루', '섬세한 취향을 따라 걷는 감성 스팟 루트', 2, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (13, '노트북 펴고 낭만 한 스푼', '작업부터 당 충전까지 책임지는 하루 코스', 2, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (14, '연희동 감성코스 한 바퀴', '혼자서도 알찬 연희동 혼놀 코스', 2, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (15, '감상에 집중하고 싶은 날', '책과 음악, 한 편의 영화로 채우는 나만의 시간', 2, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (16, '연희동 소품샵 코스', '소품샵 따라 걸으며 충전하는 소소한 기쁨', 2, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                         (17, '혼자 쉬는 평일 오후 힐링 루트', '북적이지 않아 더 좋은 평일 오후 혼놀 코스', 2, TRUE, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =================================================================
-- place_social_link
-- =================================================================
INSERT INTO place_social_links (place_id, platform, url) VALUES
                                                             (1, 'INSTAGRAM', 'https://www.instagram.com/slowly_chacha'),
                                                             (2, 'INSTAGRAM', 'https://www.instagram.com/postnobills_official'),
                                                             (3, 'INSTAGRAM', 'https://www.instagram.com/rowing_seoul'),
                                                             (4, 'INSTAGRAM', 'https://www.instagram.com/coresore_house/'),
                                                             (5, 'INSTAGRAM', 'https://www.instagram.com/doraeknot_mangwon'),
                                                             (6, 'INSTAGRAM', 'https://www.instagram.com/playground_gacha'),
                                                             (7, 'INSTAGRAM', 'https://www.instagram.com/mood_m.won'),
                                                             (8, 'INSTAGRAM', 'https://www.instagram.com/nagomi.kan'),
                                                             (9, 'INSTAGRAM', ''),
                                                             (10, 'INSTAGRAM', 'https://www.instagram.com/mogumogu_mw'),
                                                             (11, 'INSTAGRAM', 'http://www.instagram.com/yookjang_mangwon'),
                                                             (12, 'INSTAGRAM', 'https://www.instagram.com/objet_sisu'),
                                                             (13, 'INSTAGRAM', 'https://www.instagram.com/smell_smile_'),
                                                             (14, 'INSTAGRAM', 'https://www.instagram.com/natbambooks'),
                                                             (15, 'INSTAGRAM', 'https://www.instagram.com/gaga77page'),
                                                             (16, 'INSTAGRAM', 'https://www.instagram.com/scatter.books'),
                                                             (17, 'INSTAGRAM', 'http://instagram.com/gelateria_dangdo'),
                                                             (18, 'INSTAGRAM', 'https://www.instagram.com/our_little_room_'),
                                                             (19, 'INSTAGRAM', 'https://www.instagram.com/ww.store.__'),
                                                             (20, 'INSTAGRAM', ''),
                                                             (21, 'INSTAGRAM', 'https://www.instagram.com/discovergoodgoods'),
                                                             (22, 'INSTAGRAM', 'https://www.instagram.com/hokori_store'),
                                                             (23, 'INSTAGRAM', 'https://www.instagram.com/duitproject.seoul'),
                                                             (24, 'INSTAGRAM', 'https://www.instagram.com/terracewear_vintage_'),
                                                             (25, 'INSTAGRAM', 'https://www.instagram.com/__adhouse'),
                                                             (26, 'INSTAGRAM', 'https://www.instagram.com/almang_market'),
                                                             (27, 'INSTAGRAM', ''),
                                                             (28, 'INSTAGRAM', 'http://www.instagram.com/selermari_seoul'),
                                                             (29, 'INSTAGRAM', 'https://www.instagram.com/haru.heki/'),
                                                             (30, 'INSTAGRAM', 'https://www.instagram.com/ii_yeonhui'),
                                                             (31, 'INSTAGRAM', 'https://www.instagram.com/your_mind_com'),
                                                             (32, 'INSTAGRAM', 'https://www.instagram.com/poset.official'),
                                                             (33, 'INSTAGRAM', 'https://www.instagram.com/vonzrr_yeonhui'),
                                                             (34, 'INSTAGRAM', 'https://www.instagram.com/sentiment_yeonhui/profilecard'),
                                                             (35, 'INSTAGRAM', 'https://www.instagram.com/protokoll.roasters'),
                                                             (36, 'INSTAGRAM', 'https://www.instagram.com/cafe_ko.u'),
                                                             (37, 'INSTAGRAM', 'https://www.instagram.com/pourinlg_outl'),
                                                             (38, 'INSTAGRAM', 'https://www.instagram.com/allwrite_shop'),
                                                             (39, 'INSTAGRAM', 'https://www.instagram.com/geulwoll.kr'),
                                                             (40, 'INSTAGRAM', 'https://www.instagram.com/beesket_studio'),
                                                             (41, 'INSTAGRAM', 'https://www.instagram.com/collect.store'),
                                                             (42, 'INSTAGRAM', 'https://www.instagram.com/green_gongjang/'),
                                                             (43, 'INSTAGRAM', 'https://www.instagram.com/linkageburger'),
                                                             (44, 'INSTAGRAM', 'https://www.instagram.com/yeonhui_apple?igsh=MWFrYXA0MG5kdGxpdg%3D%3D&utm_source=qr'),
                                                             (45, 'INSTAGRAM', ''),
                                                             (46, 'INSTAGRAM', 'https://www.instagram.com/bare_bread/'),
                                                             (47, 'INSTAGRAM', 'https://www.instagram.com/yeonhui_espresso'),
                                                             (48, 'INSTAGRAM', 'https://www.instagram.com/lala_loodle'),
                                                             (49, 'INSTAGRAM', 'https://www.instagram.com/khakis2020'),
                                                             (50, 'INSTAGRAM', 'https://www.instagram.com/soblue_official'),
                                                             (51, 'INSTAGRAM', 'https://www.instagram.com/firstbythree'),
                                                             (52, 'INSTAGRAM', 'https://www.instagram.com/palette_salad/'),
                                                             (53, 'INSTAGRAM', 'https://www.instagram.com/grommetcoffeehouse'),
                                                             (54, 'INSTAGRAM', 'https://www.instagram.com/forfourbread'),
                                                             (55, 'INSTAGRAM', 'https://www.instagram.com/object_sangga'),
                                                             (56, 'INSTAGRAM', 'https://www.instagram.com/laikacinema');

-- =================================================================
-- place_tag
-- =================================================================
INSERT INTO place_tag (place_id, tag_id) VALUES
                                             (1, 1),(1, 7),(1, 10),(1, 11),(1, 13),(1, 16),(1, 15),
                                             (2, 1),(2, 7),(2, 10),(2, 11),(2, 12),
                                             (3, 1),(3, 8),(3, 9),(3, 11),(3, 13),
                                             (4, 1),(4, 7),(4, 9),(4, 11),(4, 12),(4, 16),
                                             (5, 1),(5, 7),(5, 9),(5, 13),(5, 16),
                                             (6, 3),(6, 28),
                                             (7, 3),(7, 28),
                                             (8, 2),(8, 19),(8, 24),
                                             (9, 2),(9, 19),
                                             (10, 2),(10, 19),
                                             (11, 2),(11, 17),
                                             (12, 5),(12, 27),
                                             (13, 5),(13, 27),
                                             (14, 4),
                                             (15, 4),
                                             (16, 4),
                                             (17, 1),(17, 7),
                                             (18, 3),(18, 28),
                                             (19, 3),(19, 28),
                                             (20, 3),(20, 28),
                                             (21, 3),(21, 28),
                                             (22, 3),(22, 28),
                                             (23, 3),(23, 28),
                                             (24, 3),(24, 29),
                                             (25, 3),(25, 29),
                                             (26, 3),(26, 28),
                                             (27, 3),(27, 29),
                                             (28, 2),(28, 17),
                                             (29, 2),(29, 19),
                                             (30, 5),(30, 26),
                                             (31, 4),
                                             (32, 3),(32, 28),
                                             (33, 1),(33, 8),(33, 9),(33, 13),(33, 14),(33, 16),
                                             (34, 1),(34, 9),(34, 10),(34, 12),(34, 13),(34, 16),
                                             (35, 1),(35, 8),(35, 14),(35, 16),
                                             (36, 1),(36, 7),(36, 8),(36, 9),(36, 11),(36, 16),
                                             (37, 1),(37, 7),(37, 8),(37, 9),(37, 12),
                                             (38, 3),(38, 28),
                                             (39, 3),(39, 28),
                                             (40, 3),(40, 28),
                                             (41, 3),(41, 28),
                                             (42, 3),(42, 28),
                                             (43, 2),(43, 20),(43, 24),
                                             (44, 4),
                                             (45, 6),
                                             (46, 2),(46, 22),
                                             (47, 1),(47, 7),(47, 12),(47, 16),
                                             (48, 2),(48, 18),
                                             (49, 3),(49, 29),
                                             (50, 4),
                                             (51, 1),(51, 7),(51, 9),(51, 11),(51, 12),
                                             (52, 2),(52, 20),
                                             (53, 1),(53, 7),(53, 8),(53, 11),(53, 16),(53, 14),
                                             (54, 2),(54, 22),
                                             (55, 3),(55, 28),
                                             (56, 5),(56, 26);

-- =================================================================
-- course_place
-- =================================================================
INSERT INTO course_place (place_order, course_id, place_id, created_at, updated_at) VALUES
                                                                                        (1, 1, 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 1, 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(4, 1, 23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 2, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 2, 25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 2, 27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 3, 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 3, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 3, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 4, 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 4, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 4, 26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 5, 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 5, 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 5, 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(4, 5, 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 6, 21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 6, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 6, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 7, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 7, 28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 7, 19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 8, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 8, 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 8, 29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 9, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 9, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 9, 22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 10, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 10, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 10, 32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(4, 10, 39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 11, 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 11, 51, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 11, 45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 12, 42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 12, 41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 12, 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 13, 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 13, 54, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 13, 48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 14, 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 14, 48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 14, 46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 15, 56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 15, 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 15, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(4, 15, 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 16, 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 16, 49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 16, 55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                        (1, 17, 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(2, 17, 47, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 17, 37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =================================================================
-- Sequence 값 업데이트 (PostgreSQL 기준)
-- =================================================================
-- 테이블에 직접 ID를 삽입했으므로, 다음 ID가 정상적으로 생성되도록 sequence를 마지막 ID 값으로 업데이트합니다.
SELECT setval('towns_id_seq', (SELECT MAX(id) FROM towns));
SELECT setval('tags_id_seq', (SELECT MAX(id) FROM tags));
SELECT setval('places_id_seq', (SELECT MAX(id) FROM places));
SELECT setval('courses_id_seq', (SELECT MAX(id) FROM courses));