-- V35: count_calculated_at을 걷어낸다 — 이 컬럼을 읽던 문장이 사라졌다.
--
-- V32가 이 컬럼을 만든 이유는 관측이 아니라 청소였다. 당시 카운트 배치는 두 문장이었고
--   (1) 활성 장소 전량을 원본에서 적재하며 이번 회차 시각을 전 행에 찍는다
--   (2) DELETE FROM place_stats WHERE count_calculated_at <> :calculatedAt
-- (2)가 (1)의 표식을 읽었다. 이번 회차에 안 찍힌 행 = 활성 장소 목록에서 빠진 장소의 잔행이다.
-- 즉 mark-and-sweep의 mark 비트였고, 전 행에 매 회차 찍는 것이 낭비가 아니라 기능이었다.
--
-- 그 우회가 필요했던 것은 적재 문장이 "지금 활성인 장소"는 알아도 "직전 회차에 있다가 이번에
-- 사라진 장소"는 모르기 때문이다. 차집합을 구할 방법이 표식뿐이었다.
--
-- 행의 주인이 어드민 쓰기 트랜잭션으로 일원화되면서 (2)가 통째로 사라졌다. 이제 장소를 내리는
-- 트랜잭션이 그 자리에서 AdminPlaceService → PlaceStatsRepository#deleteByPlaceIds로 행을 지운다.
-- 사라진 장소가 무엇인지 사라뜨린 쪽이 알고 있으니 차집합을 되짚을 일이 없고, mark의 소비자가
-- 없어졌다. 남은 것은 전 행을 쓰는 비용뿐이다.
--
-- 그 비용의 정체가 이 마이그레이션의 실익이다. InnoDB는 UPDATE의 새 값이 기존 값과 전부 같으면
-- 행을 건드리지 않는데, 회차 시각은 모든 행에서 반드시 달라지므로 그 판정을 전 행에서 무조건
-- 실패시킨다. 한 시간 동안 북마크도 리뷰도 안 붙은 장소까지 매시 다시 쓰이고, 그만큼의
-- undo·redo·binlog(ROW 포맷)가 따라온다. 컬럼이 빠지면 카운트 배치의 쓰기가 실제로 값이 바뀐
-- 장소로 좁혀진다. (좁혀지는 폭은 시간당 활동이 몇 개 장소에 퍼지느냐에 달렸고 아직 재지 않았다.)
--
-- 관측 능력은 잃지 않는다. "카운트 배치가 마지막으로 언제 돌았나"는 shedlock 테이블(V27)의
-- name='place-stats-count' 한 행에 locked_at으로 이미 기록되고, 회차마다 갱신된다. 같은 사실을
-- 장소 수만큼 복제할 이유가 없다.
--
-- ⚠️ 롤링 배포와 호환되지 않는다 — V32와 같은 성질의 제약이다. 구버전 인스턴스의
--    upsertRowsForActivePlaces·rebuildRowsFromSource는 INSERT 컬럼 목록에 count_calculated_at을
--    명시하고, updateCounts는 SET 목록에 담는다. 컬럼이 사라진 뒤 그 문장들이 돌면 ERROR 1054로
--    죽는다. 죽는 경로는 어드민 쓰기와 배치이고 사용자 조회 경로는 이 컬럼을 읽은 적이 없다.
--    무중단이 필요하면 (a) 먼저 NULL 허용으로 풀고 신버전이 값 쓰기를 멈춘 뒤 (b) 다음 배포에서
--    드롭하는 2단계로 나눌 것.
--
-- 인덱스 영향 없음: idx_place_stats_town_score·idx_place_stats_town_created 어느 쪽도 이 컬럼을
-- 담지 않는다 (V34에서 확정된 두 커버링 인덱스의 컬럼 목록에 없다).
ALTER TABLE place_stats
    DROP COLUMN count_calculated_at;
