name: Code Delivery

on:
  push:
    branches:
      - develop

jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application.yml
        run: |
          cd src/main/resources
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application.yml
        working-directory: ${{ env.working-directory }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        working-directory: ${{ env.working-directory }}

      - name: docker buildx setup
        uses: docker/setup-buildx-action@v2.9.1

      - name: Docker Hub Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:dev-latest

  deploy-cd:
    needs: deploy-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload deploy.sh to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_ACCESS_KEY }}
          source: ./scripts/deploy.sh
          target: /home/ubuntu/solply-server/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.SERVER_PUBLIC_IP }}
          key: ${{ secrets.EC2_ACCESS_KEY }}
          script: |
            echo "${{ secrets.DOCKER_COMPOSE_DEV_YML_BASE64 }}" | base64 -d > docker-compose.yml
            chmod +x ./solply-server/scripts/deploy.sh
            ./solply-server/scripts/deploy.sh "$(cat docker-compose.yml)"