name: Code Delivery

on:
  push:
    branches:
      - develop

jobs:
  deploy-ci:
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application.yml
        run: |
          cd src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application.yml
        working-directory: ${{ env.working-directory }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        working-directory: ${{ env.working-directory }}
        shell: bash

      - name: docker buildx setup
        uses: docker/setup-buildx-action@v2.9.1

      - name: Docker Hub Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:dev-latest

  deploy-cd:
    needs: deploy-ci
    runs-on: ubuntu-latest

    steps:
      - name: run docker container
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{secrets.SERVER_PUBLIC_IP}}
          key: ${{ secrets.EC2_ACCESS_KEY }}
          script: |
            # 최신 이미지 다운로드
            sudo docker pull ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_IMAGE }}
            
            # 실행 권한 부여 (777보다는 755가 안전)
            chmod +x ./deploy.sh
            
            # 배포 실행
            ./deploy.sh
            
            # 사용하지 않는 이미지 정리
            sudo docker image prune -f
            
            # 선택적: 시스템 정리
            sudo docker system prune -f

