name: Continuous Integration

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application.yml
        run: |
          # create application.yml
          cd src/main/resources
          touch ./application.yml
            
          # GitHub Actions 시크릿 변수에 설정한 값을 application.yml 파일에 작성
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application-dev.yml

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash